/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-22 21:53:01 UTC)
 * on 2014-08-11 at 14:19:22 UTC 
 * Modify at your own risk.
 */

package com.appspot.dice_with_friends.dicewithfriends.model;

/**
 * Model definition for GameProtoEntityKeyNewScore.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the dicewithfriends. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class GameProtoEntityKeyNewScore extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String entityKey;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("new_score") @com.google.api.client.json.JsonString
  private java.lang.Long newScore;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getEntityKey() {
    return entityKey;
  }

  /**
   * @param entityKey entityKey or {@code null} for none
   */
  public GameProtoEntityKeyNewScore setEntityKey(java.lang.String entityKey) {
    this.entityKey = entityKey;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getNewScore() {
    return newScore;
  }

  /**
   * @param newScore newScore or {@code null} for none
   */
  public GameProtoEntityKeyNewScore setNewScore(java.lang.Long newScore) {
    this.newScore = newScore;
    return this;
  }

  @Override
  public GameProtoEntityKeyNewScore set(String fieldName, Object value) {
    return (GameProtoEntityKeyNewScore) super.set(fieldName, value);
  }

  @Override
  public GameProtoEntityKeyNewScore clone() {
    return (GameProtoEntityKeyNewScore) super.clone();
  }

}
