/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-22 21:53:01 UTC)
 * on 2014-08-13 at 14:44:39 UTC 
 * Modify at your own risk.
 */

package com.appspot.dice_with_friends.dicewithfriends.model;

/**
 * Model definition for GameProtoInviteeEmail.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the dicewithfriends. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class GameProtoInviteeEmail extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("invitee_email")
  private java.lang.String inviteeEmail;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getInviteeEmail() {
    return inviteeEmail;
  }

  /**
   * @param inviteeEmail inviteeEmail or {@code null} for none
   */
  public GameProtoInviteeEmail setInviteeEmail(java.lang.String inviteeEmail) {
    this.inviteeEmail = inviteeEmail;
    return this;
  }

  @Override
  public GameProtoInviteeEmail set(String fieldName, Object value) {
    return (GameProtoInviteeEmail) super.set(fieldName, value);
  }

  @Override
  public GameProtoInviteeEmail clone() {
    return (GameProtoInviteeEmail) super.clone();
  }

}
